function dpsi = dpsi_Function(k_sv,k_sh,v,delta_v)
%DPSI_FUNCTION
%    DPSI = DPSI_FUNCTION(K_SV,K_SH,V,DELTA_V)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    12-Nov-2019 16:30:48

t2 = v.^2;
dpsi = (delta_v.*k_sh.*k_sv.*v.*2.927339757790822e+22)./(k_sh.*k_sv.*7.611083370256139e+21+k_sh.*t2.*3.156595046462155e+22-k_sv.*t2.*3.643029742934368e+22-k_sh.^2.*9.901e+3+k_sv.^2.*3.83074e+5);
