function dpsi = dpsi_Function(k_sv,k_sh,v,delta_v)
%DPSI_FUNCTION
%    DPSI = DPSI_FUNCTION(K_SV,K_SH,V,DELTA_V)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    05-Nov-2019 18:25:16

t2 = v.^2;
dpsi = (delta_v.*k_sh.*k_sv.*v.*2.927339757790822e22)./(k_sh.*k_sv.*7.611083370256139e21+k_sh.*t2.*3.156595046462155e22-k_sv.*t2.*3.643029742934368e22-k_sh.^2.*9.901e3+k_sv.^2.*3.83074e5);
