# 0 - standard direction use -1 for other direction
direction: 0
#number of curve points (use between 3 and 30)
num_points: 3
num_subpoints: 10
# True: show results in frame with track bars
visualization: True
# hsv interval for selecting mask
HSV_low: [115, 55, 116]
HSV_high: [160, 255, 255]
# cropping factors: width, bottom, top
cropping_factors: [0.7, 0.37, 0.53] #####[0.7, 0.37, 0.4]