function [time, ch1, ch2] = get_speedData(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [TIME, CH1, CH2] = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as column
%  vectors.
%
%  [TIME, CH1, CH2] = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  [time, ch1, ch2] = importfile("C:\Users\maxim\Documents\GitHub\picar_mum\tasks\task1\tek0000ALL.csv", [22, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 05-Nov-2019 16:59:10

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [22, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["time", "ch1", "ch2"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
time = tbl.time;
ch1 = tbl.ch1;
ch2 = tbl.ch2;
end