
########################################
# steering control gains
Kp_steering: 1.3
Kp_c_steering: 0.5
xLA_steering: 0.28
########################################
# velocity picker
vel_reference: 0.9
switch_bound: 0.3

########################################
# velocity control gains
Kp_velocity: 0.0
Kd_velocity: 0.0
