
########################################
# steering control gains
Kp_steering: 1.3
Kp_c_steering: 0.5
xLA_steering: 0.28

#simu gains
Kp_steering: 3.5
Kp_c_steering: 0.2
xLA_steering: 0.1

########################################
# velocity picker
vel_min: 0.9
vel_max: 2.5

switch_bound_slope: 0.5
switch_bound_radius: 0.9

#simu gains
switch_bound_slope: 0.8
switch_bound_radius: 0.85


########################################
# velocity control gains
#Kp_velocity: 0.027
#Kd_velocity: 0.008

#simu gains
Kp_velocity: 0.015
Kd_velocity: 0.001

