
########################################
# steering control gains corners
Kp_steering: 1.05
Kp_c_steering: 0.7
xLA_steering: 0.20


#simu gains
#Kp_steering: 3.5
#Kp_c_steering: 0.2
#xLA_steering: 0.1

########################################
# velocity picker
vel_min: 0.6 #1.5 #1.3
vel_max: 0.8 #1.6 #2.0

switch_bound_slope: 0.2
switch_bound_radius: 0.9

#simu gains
#switch_bound_slope: 0.8
#switch_bound_radius: 0.85


########################################
# velocity control gains
Kp_velocity: 0.027
Kd_velocity: 0.005

#simu gains
#Kp_velocity: 0.015
#Kd_velocity: 0.001

