########################################
#Picar04 parameters
########################################
# steering control gains
Kp_steering: 1.5 #p_gain of controller
xLA_steering: 0.25 # Look ahead distance in m of steering control
Kp_c_steering: 0.5  #gain of feed forward model term

########################################
# steering control gains
Kp_velocity: 0.12
Kd_velocity: 0.025
########################################
# min velocity
vel_reference: 0.85

