
########################################
# steering control gains
Kp_steering: 1.5
Kp_c_steering: 0.5
xLA_steering: 0.3
########################################
# velocity picker
vel_reference: 0.9
switch_bound: 1.2

########################################
# velocity control gains
Kp_velocity: 0.0
Kd_velocity: 0.0
