Rate: 20 # Hz
TagID: 3
TagSize: 0.0765 # in m
Tagtvec: [0.0, 0.0, 0.0] # translational vector from tag to reference coordinate system e.g. COM of car
Tagrmat: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0] # rotationmatrix from tag to reference coordinate system