########## explanation for crop_ratios ##########
# crop_radio_middle_x = Dx/width
# crop_ratio_top_y = Dy/height
#
# |<--              width                  -->|
#              | <-- DX  -->|
# ---------------------------------------------  ^
# |            |            |    ^            |
# |            |            |    Dy           |
# |            |            |                 |  height
# |            |____________|    v            |
# |                                           |
# |                                           |
# |                                           |  v
# ---------------------------------------------
crop_ratio_middle_x: 0.5
crop_ratio_top_y: 0.65
# masking parameters
# masking parameters blue_ball
mask_param_blue_low: [100, 215, 0]
mask_param_blue_high: [130, 255, 255]
# masking parameters green ball
mask_param_green_low: [35, 230, 20]
mask_param_green_high: [70, 255, 255]
# cicrle detection parameters
dp: 1.5
minDist: 15
param1: 50
param2: 20
min_circle_radius: 0
max_circle_radius: 20