servo_channel: 6
motor_forward_channel: 11
motor_backward_channel: 10
in_1_channel: 8
in_2_channel: 9
angle_max: 30.0
angle_min: -30.0
throttle_min: -4095
throttle_max: 4095
servo_offset: 1228
servo_gain: -13.0