min_dist_obstacle: 0.7
# steering control gains for state 1,2,3*
Kp_steering: 5
Kp_c_steering: 0.3
xLA_steering: 0.1
# velocity control gains for state 3*
Kp_distance: 0.3
Kd_distance: 0.2
Ki_distance: 0.0
