Debug: True
########################################
# steering control gains for state 1,2,3*
Kp_steering: 1.5
Kp_c_steering: 0.4
xLA_steering: 0.3
#########################################
# velocity control for state 1,2
vel_reference_line: 0.6
vel_reference_curve: 0.6
switch_bound: 0.9

########################################
# ALL DISTANCES ARE RELATED TO THE COORDINATE SYSTEM DEFINED AS THE ORIGIN (e.g. center, rear end of picar)
 # distance when state machine switches to state 3* is 2 times larger than desired obstacle distance
des_distance_to_obstacle: 0.6  # reference input for distance controller -- MOVING OBSTACLE
#des_distance_to_obstacle: 0.8  # reference input for distance controller -- STATIC OBSTACLE
# WARNING !!!!!should be larger than possible values e.g. apriltag_quatschwert !!!!!!
apriltag_quatschwert: 0.35 # ONLY CHNAGE IF YOU KNOW WHAT YOU ARE DOING

Kp_steering_apriltag: 40
########################################
# velocity control gains for state 3* -> keep distance to obstacle
Kp_distance: 0.8
Kd_distance: 1.2
Ki_distance: 0.01 #  BE AWARE THAT THE INTEGRATOR DOES NOT WORK CORRECTLY IN THE FIRST RUN
