function [t, vel_des, vel_est] = getTrackedSine(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [T, VEL_DES, VEL_EST] = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as column
%  vectors.
%
%  [T, VEL_DES, VEL_EST] = IMPORTFILE(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  [t, vel_des, vel_est] = importfile("C:\Users\paulo\Google Drive\TUHH\Master\1 Semester\Formulas and Vehicles\Abgabe3\tracking_sine.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 27-Jan-2020 22:45:05

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["t", "vel_des", "t_1", "vel_est"];
opts.SelectedVariableNames = ["t", "vel_des", "vel_est"];
opts.VariableTypes = ["double", "double", "string", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "t_1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "t_1", "EmptyFieldRule", "auto");

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
t = tbl.t;
vel_des = tbl.vel_des;
vel_est = tbl.vel_est;
end