function [time, yaw, accel_x, accel_y] = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [TIME, YAW, ACCEL_X, ACCEL_Y] = IMPORTFILE(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the data as
%  column vectors.
%
%  [TIME, YAW, ACCEL_X, ACCEL_Y] = IMPORTFILE(FILE, DATALINES) reads
%  data for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  [time, yaw, accel_x, accel_y] = importfile("C:\Users\paulo\Google Drive\TUHH\Master\1 Semester\Formulas and Vehicles\git\picar_mum\tasks\task1\Skidpad\good_Results(R=1,00)\vel=0,3_ang_real=14,89_stear=16,5.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 09-Nov-2019 01:04:12

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["time", "yaw", "time_1", "accel_x", "time_2", "accel_y"];
opts.SelectedVariableNames = ["time", "yaw", "accel_x", "accel_y"];
opts.VariableTypes = ["double", "double", "string", "double", "string", "double"];

% Specify file level properties
opts.ImportErrorRule = "omitrow";
opts.MissingRule = "omitrow";
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["time_1", "time_2"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["time_1", "time_2"], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
time = tbl.time;
yaw = tbl.yaw;
accel_x = tbl.accel_x;
accel_y = tbl.accel_y;
end